name: uber_works_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   # - images/
  # #   - images/a_dot_ham.jpeg

  # # example:
  fonts:
    - family: RobotoSlab 
      fonts:
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-Thin.ttf
        weight: 100
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-Bold.ttf
        weight: 600
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-Black.ttf
        weight: 700
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Roboto_Slab/RobotoSlab-SemiBold.ttf
        weight: 900

    - family: RobotoSerif
      fonts: 
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-Thin.ttf
        weight: 100
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Roboto_Serif/RobotoSerif-Black.ttf
        weight: 900
